# Generated by Django 3.2.16 on 2025-02-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20250129_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='post_imeges', verbose_name='Фото'),
        ),
    ]
